version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  install:
    # Install package too, so autodoc works
    - method: pip
      path: .
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - epub
