name: Dataflow Integration Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ opened, reopened, synchronize, labeled ]

jobs:
  build:
    # run on:
    #  - all pushes to main
    #  - a PR was just labeled 'test-dataflow'
    #  - a PR with 'test-dataflow' label was opened, reopened, or synchronized
    if: |
      github.event_name == 'push' ||
      github.event.label.name == 'test-dataflow' ||
      contains( github.event.pull_request.labels.*.name, 'test-dataflow')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # TODO: gcloud auth
    # TODO: pytest -vvvxs tests/test_dataflow_integration.py
