name: Run Flink Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Starts a k8s cluster with NetworkPolicy enforcement and installs both
    # kubectl and helm
    #
    # ref: https://github.com/jupyterhub/action-k3s-helm/
    - uses: jupyterhub/action-k3s-helm@v3
      with:
        metrics-enabled: false
        traefik-enabled: false
        docker-enabled: true

    - name: Setup FlinkOperator
      run: |
        helm repo add flink-operator-repo https://downloads.apache.org/flink/flink-kubernetes-operator-1.1.0
        helm install flink-kubernetes-operator flink-operator-repo/flink-kubernetes-operator --wait

        kubectl get pod -A
        kubectl get crd -A
