name: Run Flink Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Starts a k8s cluster with NetworkPolicy enforcement and installs both
    # kubectl and helm
    #
    # ref: https://github.com/jupyterhub/action-k3s-helm/
    - uses: jupyterhub/action-k3s-helm@v3
      with:
        metrics-enabled: false
        traefik-enabled: false
        docker-enabled: true

    - name: Setup CertManager
      run: |
        # Setup cert-manager, required by Flink Operator
        CERT_MANAGER_VERSION=1.9.1
        kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v${CERT_MANAGER_VERSION}/cert-manager.yaml

    - name: Wait for CertManager to be ready
      uses: jupyterhub/action-k8s-await-workloads@v1
      with:
        timeout: 150
        max-restarts: 1

    - name: Setup FlinkOperator
      run: |
        FLINK_OPERATOR_VERSION=1.1.0
        helm repo add flink-operator-repo https://downloads.apache.org/flink/flink-kubernetes-operator-${FLINK_OPERATOR_VERSION}
        helm install flink-kubernetes-operator flink-operator-repo/flink-kubernetes-operator --wait

        kubectl get pod -A
        kubectl get crd -A

    - name: Wait for FlinkOperator to be ready
      uses: jupyterhub/action-k8s-await-workloads@v1
      with:
        timeout: 150
        max-restarts: 1
